version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12 # the primary container, where your job's comm
        environment:
          DATABASE_URL: postgres://psqluser:psqlpassword@localhost:5432/psdb
          JWT_SECRET: secretJwt
          API_PORT: 3000
          API_HOST: localhost
          API_PROTOCOL: http
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
      - image: 'circleci/postgres:9.6.2-alpine'
        environment:
          POSTGRE_USER: psqluser
          POSTGRE_PASSWORD: psqlpassword
          POSTGRE_DB: psdb
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp && yarn install
      - run: yarn test:e2e
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lcok" }}
          paths:
            - ./node_modules
